# Welcome to Audioguide!
#

# Site settings
title: SICILIA MUSEI Audio Guide
email: info@giannimessina.it
description: > # this means to ignore newlines until "baseurl:"
  A web-based audio guide.
#baseurl: "/audioguide" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
#url: "https://giannimessina.github.io" # the base hostname & protocol for your site
logo: "/assets/img/logo/audio-guide.png"
twitter_username: giannimessina
github_username:  giannimessina
menu_heading: "Seleziona un numero"
menu_heading_en: "Select a number"

index_page_text: "Seleziona un numero per iniziare."
index_page_text_en: "Select a number to start ..."

headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Multiple languages
gems:               ['jekyll-multiple-languages']

languages:          ['it', 'en']

# If not config, the first of languages will be the default
language_default:   'it'


# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
